name: Create Release
description: Create GitHub release and upload packaged artifacts

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Get version info
      id: version
      shell: bash
      run: |
        chromium_version=$(cat ungoogled-chromium/chromium_version.txt)
        ungoogled_revision=$(cat ungoogled-chromium/revision.txt)
        version="${chromium_version}-${ungoogled_revision}"
        echo "version=${version}" >> $GITHUB_OUTPUT
        echo "chromium_version=${chromium_version}" >> $GITHUB_OUTPUT
        echo "ungoogled_revision=${ungoogled_revision}" >> $GITHUB_OUTPUT
        echo "release_tag=v${version}" >> $GITHUB_OUTPUT

    - name: Download AppImage artifacts
      uses: actions/download-artifact@v4
      with:
        name: ungoogled-chromium-${{ steps.version.outputs.version }}-x86_64-AppImage
        path: ./release/

    - name: Download tar.xz artifacts
      uses: actions/download-artifact@v4
      with:
        name: ungoogled-chromium-${{ steps.version.outputs.version }}-x86_64-linux
        path: ./release/

    - name: List release files
      shell: bash
      run: |
        echo "Release files:"
        ls -la release/

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.version.outputs.release_tag }}
        name: ungoogled-chromium ${{ steps.version.outputs.version }} Linux
        draft: false
        prerelease: false
        files: |
          release/ungoogled-chromium-${{ steps.version.outputs.version }}-x86_64.AppImage
          release/ungoogled-chromium-${{ steps.version.outputs.version }}-x86_64.AppImage.zsync
          release/ungoogled-chromium-${{ steps.version.outputs.version }}-x86_64_linux.tar.xz
