name: Build Linux AppImage for ungoogled-chromium
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  prep:
    name: Prepare resources
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - id: build_part_00
        name: build_part_00 (prepare only)
        uses: ./.github/actions/build
        with:
          prepare-only: true

  build_part_01:
    name: build_part_01
    runs-on: ubuntu-latest
    needs: [prep]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: docker/setup-buildx-action@v3
      - uses: ./.github/actions/build

  build_part_02:
    name: build_part_02
    runs-on: ubuntu-latest
    needs: [build_part_01]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: docker/setup-buildx-action@v3
      - uses: ./.github/actions/build

  build_part_03:
    name: build_part_03
    runs-on: ubuntu-latest
    needs: [build_part_02]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: docker/setup-buildx-action@v3
      - uses: ./.github/actions/build

  build_part_04:
    name: build_part_04
    runs-on: ubuntu-latest
    needs: [build_part_03]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: docker/setup-buildx-action@v3
      - uses: ./.github/actions/build

  build_part_05:
    name: build_part_05
    runs-on: ubuntu-latest
    needs: [build_part_04]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: docker/setup-buildx-action@v3
      - uses: ./.github/actions/build

  build_part_06:
    name: build_part_06
    runs-on: ubuntu-latest
    needs: [build_part_05]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: docker/setup-buildx-action@v3
      - uses: ./.github/actions/build

  build_part_07:
    name: build_part_07
    runs-on: ubuntu-latest
    needs: [build_part_06]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: docker/setup-buildx-action@v3
      - uses: ./.github/actions/build

  build_part_08:
    name: build_part_08
    runs-on: ubuntu-latest
    needs: [build_part_07]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: docker/setup-buildx-action@v3
      - uses: ./.github/actions/build

  build_part_09:
    name: build_part_09
    runs-on: ubuntu-latest
    needs: [build_part_08]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: docker/setup-buildx-action@v3
      - uses: ./.github/actions/build

  build_part_10:
    name: build_part_10
    runs-on: ubuntu-latest
    needs: [build_part_09]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: docker/setup-buildx-action@v3
      - uses: ./.github/actions/build

  package:
    name: Package AppImage
    runs-on: ubuntu-latest
    needs: [build_part_10]
    steps:
      - uses: ./.github/actions/package

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [package]
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'))
    steps:
      - uses: ./.github/actions/release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
